global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'route-monitor'
    static_configs:
      - targets: ['exporter:9108']
        labels:
          service: 'route-monitor'
          environment: 'production'
    
    # Scrape metrics from the exporter
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s